### PR TITLE
create/use enums instead of magic strings

### PR DESCRIPTION
**Pull request by dcrousso**

### CODE REVIEW

**Comment by mistermoe** [comment]
@ALRubinger we can get most of the benefits that we'd get from enums just by using `JSDoc`. almost all code editors read JSDoc and use it to provide intellisense. e.g. 

image

**Comment by dcrousso** [comment]
i still think there's some benefit in the developer being able to check at runtime what things they could provide to `web5.did.create()` without having to call it and check if it throws

**Comment by ALRubinger** [comment]
Thanks! This is awesome for removing the need for free-floating Strings. It does still force the user to a decision about something they may not understand or care about: choosing a DID method. Made my case on opting for a sensible default there in #31 - thanks y'all!

**Comment by ALRubinger** [comment]
We're shipping the Quickstart without this in place; when done, please open an issue on the developer.tbd.website repo to update the Quickstart w/ this syntax - thanks!

**Comment by dcrousso** [comment]
handled by #40

**Pull request closed without merging**
