### PR TITLE
adding subscriptions to web5-js

### PR DESCRIPTION
**Pull request by andorsk**
initial subscriptions PR. Do **NOT** merge, but used for transparency to show some of the API's and interfaces design for users when using the subscriptions interface. Open for feedback and discussion. Will have some updates in the near future.

See the documentation here: https://github.com/getZION/web5-js/tree/ask/subscription/packages/api#web5dwnsubscriptioncreaterequest for intended use.

### CODE REVIEW

**Comment by andorsk** [comment]
fixing history here. Give me a sec.

**Comment by andorsk** [comment]
@finn-tbd trying to test this locally, and running into some issues due to all the updates to authorization in `dwn-sdk-js` at the latest.  Do we have an idea of when the rest of web5-js will be up to date with the latest dwn-sdk-js? It's hard to test this PR until things have gotten more up to date with the latest.

**Comment by finn-tbd** [comment]
Looks like @thehenrytsai made these changes to dwn-sdk-js. Maybe he knows the answer?

**Comment by frankhinek** [comment]
Still in Draft state.  @andorsk any update on timing for this?

**Comment by andorsk** [comment]
@frankhinek haven't tested this in a while, but this was blocked by two things: 

1. My notes https://github.com/TBD54566975/web5-js/pull/228#issuecomment-1743132196. Guessing they moved since then, but I haven't checked.
2. https://github.com/TBD54566975/dwn-sdk-js/pull/508, which was kinda on hold for a bit for a number of reasons. 1) deprioritized on my end, but still want to get it done 2) it was relying on a lot of the permissions/authorization work, which was moving around a lot. Assuming that's stabilized a little more now. On a call with Liran today to discuss how to move this forward quicker. Otherwise, I can just get to this on the weekends.

**Comment by frankhinek** [comment]
@LiranCohen requested keeping open for now as a reminder to circle back and continue work

**Comment by LiranCohen** [comment]
Closing in favor of: https://github.com/TBD54566975/web5-js/pull/433

**Pull request closed without merging**
