### PR TITLE
speed up and rebalance CI flow

### PR DESCRIPTION
**Pull request by shamilovtim**
speeds up and rebalances the CI flow
entire run is now 18% faster

### CODE REVIEW

**Review by LiranCohen — APPROVED** [review]
Nice! Speed up in CI is always a win!

For my knowledge, is there any reason not to group all of the various `agent` packages together? Would that make things slower? Just curious of the groupings have some sort of logic around them or if it's mostly based on the speed of the run.

**Comment by shamilovtim** [comment]
> Nice! Speed up in CI is always a win!
> 
> For my knowledge, is there any reason not to group all of the various `agent` packages together? Would that make things slower? Just curious of the groupings have some sort of logic around them or if it's mostly based on the speed of the run.

no reason to group package together based on logic unless the tests are not isolated and need to be run in order. test balance comes from test timings. in better systems than github actions the CI is able to infer test timing from output and auto rebalance. with github actions you have to balance manually.

**Comment by LiranCohen** [comment]
> test balance comes from test timings. 

Yeah that's what i figured.

> in better systems than github actions the CI is able to infer test timing from output and auto rebalance. with github actions you have to balance manually

Glad you're keeping tabs on this! 18% is a huge gain! 🎸

**Review by thehenrytsai — APPROVED** [review]
🎸 
🙏 
Massive thanks! QoL improvements are powerful and always welcome!

**Pull request merged**
