### PR TITLE
added option to web5 connect to allow custom dwn

### PR DESCRIPTION
**Pull request by andorsk**
related to https://github.com/TBD54566975/web5-js/issues/162

### CODE REVIEW

**Comment by andorsk** [comment]
added additional overrides for more options.

**Comment by frankhinek** [comment]
With PR #168 merged, it is possible to override every component of the underlying `Web5Agent` that is used with the Web5 API.

One thing to note is that the implementation of the Connect Protocol is a fast-follow for PR 168, so you'll see some stubbing in `Web5.connect()` for now.  This should be done fairly quickly.

Kitchen sink example [here](https://github.com/TBD54566975/web5-js/blob/main/packages/api/tests/utils/test-user-agent.ts).

Simpler example:
```typescript
// Customize DWN stores:
const messageStore = new MessageStoreLevel({ blockstoreLocation: 'data/dwn/message-store', indexLocation: 'data/dwn/message-index' });
const dataStore = new DataStoreLevel({ blockstoreLocation: 'data/dwn/data-store' });
const eventLog = new EventLogLevel({ location: 'data/dwn/event-log' });

// Instantiate DWN using stores:
const dwn = await Dwn.create({ messageStore, dataStore, eventLog });
const dwnManager = await DwnManager.create({ dwn: mockDwn });

// Create an Agent using the customized DWN:
const agent = await Web5UserAgent.create({ dwnManager });

// Create a customized Identity & DID:
const alice = await testAgent.agent.identityManager.create({
  name      : 'Alice',
  didMethod : 'ion',
  kms       : 'local'
});

// Call connect() with the custom agent.
const { web5, did } = await Web5.connect({ agent, connectedDid : alice.did });
```

One question @andorsk : Do you think you'd typically want to override _JUST_ the DWN instance such that it might make sense to have that option for `connect()` options?  In other words, keep everything else the same but use a customized DWN instance.

**Comment by frankhinek** [comment]
@andorsk will close for now since this PR was for the pre-refactor code base.  Still very interested in your thoughts on the question of passing _just_ a custom DWN instance in to `Web5.connect()`.  Please reach out on Discord.

**Comment by andorsk** [comment]
awesome. Thanks Frank! Will ping you.

**Comment by andorsk** [comment]
> With PR #168 merged, it is possible to override every component of the underlying `Web5Agent` that is used with the Web5 API, including with `Web5.connect()`.
> 
> One thing to note is that the implementation of the Connect Protocol is a fast-follow for PR 168, so you'll see some stubbing in `Web5.connect()` for now. This should be done fairly quickly.
> 
> Kitchen sink example [here](https://github.com/TBD54566975/web5-js/blob/main/packages/api/tests/utils/test-user-agent.ts).
> 
> Simpler example:
> 
> ```ts
> // Customize DWN stores:
> const messageStore = new MessageStoreLevel({ blockstoreLocation: 'data/dwn/message-store', indexLocation: 'data/dwn/message-index' });
> const dataStore = new DataStoreLevel({ blockstoreLocation: 'data/dwn/data-store' });
> const eventLog = new EventLogLevel({ location: 'data/dwn/event-log' });
> 
> // Instantiate DWN using stores:
> const dwn = await Dwn.create({ messageStore, dataStore, eventLog });
> const dwnManager = await DwnManager.create({ dwn: mockDwn });
> 
> // Create an Agent using the customized DWN:
> const agent = await Web5UserAgent.create({ dwnManager });
> 
> // Create a customized Identity & DID:
> const alice = await agent.identityManager.create({
>   name      : 'Alice',
>   didMethod : 'ion',
>   kms       : 'local'
> });
> 
> // Call connect() with the custom agent.
> const { web5, did } = await Web5.connect({ agent, connectedDid : alice.did });
> ```
> 
> One question @andorsk : Do you think you'd typically want to override _JUST_ the DWN instance such that it might make sense to have `dwn` as a property to be passed into `connect()`? In other words, keep other defaults except for the customized DWN instance.

@frankhinek possibly. The initial impetus for my changes was to address basically the core of this refactor. Let me try out the updates and see if there's any changes required.

**Pull request closed without merging**
