### PR TITLE
adding credentials package to web5-js

### PR DESCRIPTION
**Pull request by nitro-neal**
# Summary
Integrate `pex` SSI objects within the `credentials` package of web5 and provide an SSI SDK

The `types.ts` file in the credential package exports web5 objects as wrapped pex objects
This allows users to only need to import web5 and not pex, and we can add abstractions around pex lib as needed.
### VerifiableCredential Creation and Verification

The `VerifiableCredential` class provides methods for the creation, handling, and signing of Verifiable Credentials (VCs) in JWT format.
- **VerifiableCredential.create**: Creates a Verifiable Credential (VC) in JWT format.
- **VerifiableCredential.validatePayload**: Validates the structure and integrity of a Verifiable Credential payload.
- **VerifiableCredential.verify**: Verifies the integrity of a VC JWT.
- **VerifiableCredential.decode**: Decodes a VC JWT into its constituent parts: header, payload, and signature.

### VP Creation and Verification

The `VerifiablePresentation` class provides utility methods for creation and handling Verifiable Presentations (VPs) in JWT format.
- **VerifiablePresentation.create**: Creates a Verifiable Presentation (VP) in JWT format from a presentation definition and set of credentials.
- **VerifiablePresentation.verify**: Verifies the integrity of a VP JWT.
- **VerifiablePresentation.validatePayload**: Validates the structure and integrity of a Verifiable Presentation payload.
- **VerifiablePresentation.decode**: Decodes a VP JWT into its constituent parts: header, payload, and signature.

### Presentation Exchange Helpers

These methods assist in evaluating verifiable credentials and presentations against specified presentation definitions.

- **VerifiableCredential.evaluateCredentials**: Evaluates a set of verifiable credentials against a specified presentation definition.
- **VerifiablePresentation.evaluatePresentation**: Evaluates a given Verifiable Presentation against a specified presentation definition.

### Verifiable Credentials and Presentations Library
Note: you do not have to use the functions to create SSI objects, you can instead create them yourselves with the boilerplate types in types.ts

```typescript
      const vc: VerifiableCredentialV1 = {
        '@context'          : ['https://www.w3.org/2018/credentials/v1'],
        'id'                : 'my-cred',
        'type'              : ['VerifiableCredential'],
        'issuer'            : 'did:key:123',
        'issuanceDate'      : getCurrentXmlSchema112Timestamp(),
        'credentialSubject' : {
          'btcAddress': 'btcAddress123'
        }
      };
```
### Signer Options Object

The `Signer` represents a function that takes a byte array as input and returns a promise that resolves to a byte array, representing the signature of the input data.

### Type Definition

```typescript
type Signer = (data: Uint8Array) => Promise<Uint8Array>;
```

This change also allows a full PE by users using boilerplate ssi objects. A full Presentation Exchange is available as a new unit test `presentationexchange.spec.ts`

### CODE REVIEW

**Comment by nitro-neal** [comment]
image
Tests Passing

**Review by frankhinek — DISMISSED** [review]
Notes:
- Switched to using `Convert` utility from the `@web5/common` package instead of `Encoder` from `@tbd54566975/dwn-sdk-js`.
- A devDependency on `@tbd54566975/dwn-sdk-js` was added to the PresentationExchange test but not added to `package.json`.  Doesn't need to be fixed since it was swapped for `Convert` but something to keep an eye on.

And a a few minor changes:
- Added comments to the newly added utility functions. @nitro-neal double-check that the explanations and usage examples are accurate.
- Used exact dependency version for `@sphereon/pex`.
- Updated formatting, word wrap, and code style to match SDK conventions.

**Comment by nitro-neal** [comment]
## Credentials


### VC Creation and Verification

The `VC` class provides methods for the creation, handling, and signing of Verifiable Credentials (VCs) in JWT format.

- **VC.createVerifiableCredentialJwt**: Creates a Verifiable Credential (VC) in JWT format.
- **VC.decodeVerifiableCredentialJwt**: Decodes a VC JWT into its constituent parts: header, payload, and signature.
- **VC.verifyVerifiableCredentialJwt**: Verifies the integrity of a VC JWT.
- **VC.validateVerifiableCredentialPayload**: Validates the structure and integrity of a Verifiable Credential payload.

### VP Creation and Verification

The `VP` class provides utility methods for creation and handling Verifiable Presentations (VPs) in JWT format.

- **VP.createVerifiablePresentationJwt**: Creates a Verifiable Presentation (VP) in JWT format from a presentation definition and set of credentials.
- **VP.decodeVerifiablePresentationJwt**: Decodes a VP JWT into its constituent parts: header, payload, and signature.
- **VP.verifyVerifiablePresentationJwt**: Verifies the integrity of a VP JWT.
- **VP.validateVerifiablePresentationPayload**: Validates the structure and integrity of a Verifiable Presentation payload.

### Presentation Exchange Helpers

These methods assist in evaluating verifiable credentials and presentations against specified presentation definitions.

- **VC.evaluateCredentials**: Evaluates a set of verifiable credentials against a specified presentation definition.
- **VP.evaluatePresentation**: Evaluates a given Verifiable Presentation against a specified presentation definition.

### Verifiable Credentials and Presentations Library
Note: you do not have to use the functions to create SSI objects, you can instead create them yourselves with the boilerplate types in types.ts

### Signer Options Object

The `Signer` represents a function that takes a byte array as input and returns a promise that resolves to a byte array, representing the signature of the input data.

### Type Definition

```typescript
type Signer = (data: Uint8Array) => Promise<Uint8Array>;
```

**Review by mistermoe — APPROVED** [review]
🎖️ 💯 🍖 🌞

**Pull request merged**
